version: '2.1'

services:
  localstack:
    image: riseup_localstack
    ports:
      - "4567-4584:4567-4584"
      - "${PORT_WEB_UI-9080}:${PORT_WEB_UI-9080}"
    environment:
      - SERVICES=sqs,sns
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=9080
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/private/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
